### ISSUE TITLE
Unable to generate retention curve based on profile

### ISSUE THREAD

**Issue by Klod** [ESeufert/theseus_growth#10]
I have tried to follow your instructions provided in the library but get this error below? Can you advise on how to resolve?

<img width="807" alt="Screen Shot 2020-07-10 at 6 13 16 PM" src="https://user-images.githubusercontent.com/2121449/87213395-80093400-c2d9-11ea-8026-8c7c489c6d68.png">

**Comment by ESeufert** [comment]
This is a known bug, I'm going to try to push a fix next week

**Comment by ESeufert** [comment]
This is fixed
