### ISSUE TITLE
Optimal parameters not found

### ISSUE THREAD

**Issue by 10Evansr** [ESeufert/theseus_growth#2]
Thanks for this library! In playing around a bit tonight, I ran into an issue where one fit fails with a `Exception: Unable to process retention curve with exp function`  and breaks the `create_profile` method. What are your thoughts on the library swallowing the error instead of propagating it up and continue with trying to fit the inputs?

(Sorry, originally thought the error was coming out of scipy without reading the whole traceback and suggested something irrelevant)

**Comment by ESeufert** [comment]
That's a good idea. I will think about how to handle that, but you are right -- the method should continue

**Comment by ESeufert** [comment]
should be fixed now
