### ISSUE TITLE
Decouple test suite from project code.

### ISSUE THREAD

**Issue by GuillaumeLegoy** [ESeufert/theseus_growth#3]
Hello,

Right now test functions are part of the project code located in the __init__.py file.

A separate test folder could be created and ran later as part of a CI/CD pipeline, using the purest library for instance. Advantages:

- more clarity
- easier to debug
- shorter modules
- dependencies management: test libraries can be decoupled from project libraries with Poetry.

Regards,

Guillaume

**Comment by ESeufert** [comment]
yeah I'm working on that at the moment. Up to launch I was just testing everything via Jupyter Notebooks but this is on my to-do list.

**Comment by GuillaumeLegoy** [comment]
Sounds great! If that helps free your time for other improbements I can definitely create a pull request for this. Let me know.

**Comment by ESeufert** [comment]
split out functionality into modules although that doesn't really help with testing
