### ISSUE TITLE
exp vs expit

### ISSUE THREAD

**Issue by yavuzacikalin** [ESeufert/theseus_growth#9]
@ESeufert I was skimming through the code and it looks like scipy.special.expit may be used in place of np.exp in a few places. 

My understanding of scipy's expit as a convenience function is: `expit(x) = np.exp(x)/(1+np.exp(x))`

e.g., I think the Weibull function should look like `(k/l) * ((x/l) ** (k - 1)) * np.exp(- (x/l) ** k)`

**Comment by ESeufert** [comment]
Good catch -- fixed
